// GENERATED by behavior-contracts (go-typed-native) — the BC-OWNED shared wire types. A covered module
// generated with --shared-types-import imports this; a separate leaf-transport package returns its
// WireValue. Self-contained + runtime-free.
package wire

import "strconv"

// Probe kinds — the outcome of classifying one wire attribute against a declared field type.
const (
	probeGot    uint8 = 0 // present; the wire variant matches the declared type
	probeWrong  uint8 = 1 // present but a different wire variant (carries ActualWireType + Raw)
	probeAbsent uint8 = 2 // no attribute for this field
	probeNull   uint8 = 3 // present as the producer's null variant (opt → None; required → mismatch)
)

// Probe RESULT structs — concrete data the WireValue classifiers hand back; the de-box reads .Kind /
// .Got / .ActualWireType / .Raw (exported fields).

// StringProbe / NumberProbe / BoolProbe — a scalar probe result. Got holds the matched value (a
// NumberProbe's Got is the raw numeric text; the de-box parses + range-checks it). ActualWireType is the
// producer's own wire tag (a free string, e.g. a DynamoDB "S"/"N"/"BOOL"); Raw is the offending value
// stringified. Concrete structs — no boxed Value crosses the seam.
type StringProbe struct {
	Kind           uint8
	Got            string
	ActualWireType string
	Raw            string
}

type NumberProbe struct {
	Kind           uint8
	Got            string
	ActualWireType string
	Raw            string
}

type BoolProbe struct {
	Kind           uint8
	Got            bool
	ActualWireType string
	Raw            string
}

// RowProbe / ListProbe — a composite probe result: a nested wire map (a DynamoDB "M") or wire array (an
// "L"). Got is the consumer's CONCRETE WireRow / WireList (a value type — no boxed Value, no
// interface); the inline de-box probes it directly.
type RowProbe struct {
	Kind           uint8
	Got            WireRow
	ActualWireType string
	Raw            string
}

type ListProbe struct {
	Kind           uint8
	Got            WireList
	ActualWireType string
	Raw            string
}

// WireValue — the BC-OWNED generic result the consumer's single op-agnostic transport builds + returns
// (WireStr/WireNum/WireInt/WireFloat/WireBool/WireNull/WireRowOf/WireListOf) and implements NOTHING over.
// A self-contained tagged union (no untyped box, no bc-runtime Value); numbers carry raw text (BC parses +
// range-checks → overflow is BC's to detect). Composite = nested Entries (row) / Items (list).
type WireValue struct {
	kind    uint8
	str     string
	num     string
	bl      bool
	Entries []WireField
	Items   []WireValue
}

type WireField struct {
	Key string
	Val WireValue
}

// WireRow / WireList — a wire map / array handle over a SHARED slice backing (value type; probes return the
// bc probe RESULT structs). The generated de-box probes them by declared field / element.
type WireRow struct {
	entries []WireField
}

type WireList struct {
	items []WireValue
}

const (
	wireNull uint8 = 0
	wireStr  uint8 = 1
	wireNum  uint8 = 2
	wireBool uint8 = 3
	wireRow  uint8 = 4
	wireList uint8 = 5
)

// constructors the consumer's transport uses to build the result (numbers ride as raw text).
func WireStr(s string) WireValue          { return WireValue{kind: wireStr, str: s} }
func WireNum(s string) WireValue          { return WireValue{kind: wireNum, num: s} }
func WireInt(n int64) WireValue           { return WireValue{kind: wireNum, num: strconv.FormatInt(n, 10)} }
func WireFloat(f float64) WireValue       { return WireValue{kind: wireNum, num: strconv.FormatFloat(f, 'g', -1, 64)} }
func WireBool(b bool) WireValue           { return WireValue{kind: wireBool, bl: b} }
func WireNull() WireValue                 { return WireValue{kind: wireNull} }
func WireRowOf(fields []WireField) WireValue { return WireValue{kind: wireRow, Entries: fields} }
func WireListOf(items []WireValue) WireValue { return WireValue{kind: wireList, Items: items} }

func (w *WireValue) wireTag() string {
	switch w.kind {
	case wireStr:
		return "S"
	case wireNum:
		return "N"
	case wireBool:
		return "BOOL"
	case wireRow:
		return "M"
	case wireList:
		return "L"
	default:
		return "NULL"
	}
}
func (w *WireValue) wireRaw() string {
	switch w.kind {
	case wireStr:
		return w.str
	case wireNum:
		return w.num
	case wireBool:
		if w.bl {
			return "true"
		}
		return "false"
	case wireNull:
		return "null"
	default:
		return "[composite]"
	}
}

// the top result is always present; field/elem probes share the same classifiers over *WireValue (nil = absent).
func (w WireValue) AsString() StringProbe { return probeStringOf(&w) }
func (w WireValue) AsNumber() NumberProbe { return probeNumberOf(&w) }
func (w WireValue) AsBool() BoolProbe     { return probeBoolOf(&w) }
func (w WireValue) AsRow() RowProbe       { return probeRowOf(&w) }
func (w WireValue) AsList() ListProbe     { return probeListOf(&w) }

func (r WireRow) get(field string) *WireValue {
	for i := range r.entries {
		if r.entries[i].Key == field {
			return &r.entries[i].Val
		}
	}
	return nil
}
func (r WireRow) Keys() []string {
	ks := make([]string, len(r.entries))
	for i := range r.entries {
		ks[i] = r.entries[i].Key
	}
	return ks
}
func (r WireRow) ProbeString(field string) StringProbe { return probeStringOf(r.get(field)) }
func (r WireRow) ProbeNumber(field string) NumberProbe { return probeNumberOf(r.get(field)) }
func (r WireRow) ProbeBool(field string) BoolProbe     { return probeBoolOf(r.get(field)) }
func (r WireRow) ProbeRow(field string) RowProbe       { return probeRowOf(r.get(field)) }
func (r WireRow) ProbeList(field string) ListProbe     { return probeListOf(r.get(field)) }

func (l WireList) Len() int                     { return len(l.items) }
func (l WireList) ElemString(i int) StringProbe { return probeStringOf(&l.items[i]) }
func (l WireList) ElemNumber(i int) NumberProbe { return probeNumberOf(&l.items[i]) }
func (l WireList) ElemBool(i int) BoolProbe     { return probeBoolOf(&l.items[i]) }
func (l WireList) ElemRow(i int) RowProbe       { return probeRowOf(&l.items[i]) }
func (l WireList) ElemList(i int) ListProbe     { return probeListOf(&l.items[i]) }

// the ONE classifier per kind, over *WireValue (nil = absent attribute/element). The BC-owned variant IS
// the wire tag — no consumer classification.
func probeStringOf(w *WireValue) StringProbe {
	if w == nil {
		return StringProbe{Kind: probeAbsent}
	}
	switch w.kind {
	case wireStr:
		return StringProbe{Kind: probeGot, Got: w.str, ActualWireType: "S", Raw: w.str}
	case wireNull:
		return StringProbe{Kind: probeNull, ActualWireType: "NULL", Raw: "null"}
	default:
		return StringProbe{Kind: probeWrong, ActualWireType: w.wireTag(), Raw: w.wireRaw()}
	}
}
func probeNumberOf(w *WireValue) NumberProbe {
	if w == nil {
		return NumberProbe{Kind: probeAbsent}
	}
	switch w.kind {
	case wireNum:
		return NumberProbe{Kind: probeGot, Got: w.num, ActualWireType: "N", Raw: w.num}
	case wireNull:
		return NumberProbe{Kind: probeNull, ActualWireType: "NULL", Raw: "null"}
	default:
		return NumberProbe{Kind: probeWrong, ActualWireType: w.wireTag(), Raw: w.wireRaw()}
	}
}
func probeBoolOf(w *WireValue) BoolProbe {
	if w == nil {
		return BoolProbe{Kind: probeAbsent}
	}
	switch w.kind {
	case wireBool:
		return BoolProbe{Kind: probeGot, Got: w.bl, ActualWireType: "BOOL", Raw: w.wireRaw()}
	case wireNull:
		return BoolProbe{Kind: probeNull, ActualWireType: "NULL", Raw: "null"}
	default:
		return BoolProbe{Kind: probeWrong, ActualWireType: w.wireTag(), Raw: w.wireRaw()}
	}
}
func probeRowOf(w *WireValue) RowProbe {
	if w == nil {
		return RowProbe{Kind: probeAbsent}
	}
	switch w.kind {
	case wireRow:
		return RowProbe{Kind: probeGot, Got: WireRow{entries: w.Entries}, ActualWireType: "M"}
	case wireNull:
		return RowProbe{Kind: probeNull, ActualWireType: "NULL", Raw: "null"}
	default:
		return RowProbe{Kind: probeWrong, ActualWireType: w.wireTag(), Raw: w.wireRaw()}
	}
}
func probeListOf(w *WireValue) ListProbe {
	if w == nil {
		return ListProbe{Kind: probeAbsent}
	}
	switch w.kind {
	case wireList:
		return ListProbe{Kind: probeGot, Got: WireList{items: w.Items}, ActualWireType: "L"}
	case wireNull:
		return ListProbe{Kind: probeNull, ActualWireType: "NULL", Raw: "null"}
	default:
		return ListProbe{Kind: probeWrong, ActualWireType: w.wireTag(), Raw: w.wireRaw()}
	}
}
