#![allow(dead_code, unused_imports, non_snake_case, clippy::all)]
// GENERATED by litedbmodel codegen — the RUST COMPANION for `generated_feed` (epic #123/#124).
// bc emits the runtime-free native module (ports + de-box runner + wire traits); litedbmodel emits
// THIS companion — the boundary-injected node_* handlers + wire adapter (bc C4). Every node_*
// delegates to litedbmodel_runtime's op-agnostic Driver-backed executors (the exec SSoT); the wire
// classification is single-sourced in the runtime and bridged here by the wire_impls! macro (the
// orphan rule forbids the module-local wire trait impls living in the runtime crate).
use super::generated_feed::*;
use litedbmodel_runtime::{Driver, RuntimeError, SqlFailure, Value, Wire};

const DIALECT: &str = "sqlite";

litedbmodel_runtime::wire_impls!();

/// Map a runtime SQL failure to the module-local BehaviorError (byte-equal codes: the bc runner
/// re-wraps a node failure as OP_FAILED regardless, so only the message/detail cross this seam).
fn cvt(e: SqlFailure) -> BehaviorError { BehaviorError::new(e.kind, e.message) }
fn cvt_rel(e: RuntimeError) -> BehaviorError { BehaviorError::new("RELATION_ERROR", e.message().to_string()) }

pub struct Rt<'a> { driver: &'a dyn Driver }
impl<'a> HandlerNRPostsWithAuthor for Rt<'a> {
    type Wire = Wire;
    fn node_n0(&self, ports: &PortsNRPostsWithAuthorN0, _bound: Option<String>) -> Result<Wire, BehaviorError> {
        litedbmodel_runtime::exec(&litedbmodel_runtime::for_driver(self.driver), &ports.f_sql, &[litedbmodel_runtime::wp(&ports.f_p0)], litedbmodel_runtime::ExecMode::Rows).map_err(cvt)
    }
    fn node_n1(&self, ports: &PortsNRPostsWithAuthorN1, _bound: Option<String>) -> Result<Wire, BehaviorError> {
        litedbmodel_runtime::exec(&litedbmodel_runtime::for_driver(self.driver), &ports.f_sql, &[litedbmodel_runtime::wp(&ports.f_p0)], litedbmodel_runtime::ExecMode::Rows).map_err(cvt)
    }
}

/// The litedbmodel-consumer entry: build the runtime-backed handler for `PostsWithAuthor`. The consumer
/// calls `run_native_raw_struct_PostsWithAuthor(&handler(driver), in_)` — supplying NO node_* itself.
pub fn handler(driver: &dyn Driver) -> Rt<'_> { Rt { driver } }
