#![allow(dead_code, unused_imports, non_snake_case, clippy::all)]
// GENERATED by litedbmodel codegen — the RUST COMPANION for `generated_txnestedcreate` (epic #123/#124).
// bc emits the runtime-free native module (ports + de-box runner + wire traits); litedbmodel emits
// THIS companion — the boundary-injected node_* handlers + wire adapter (bc C4). Every node_*
// delegates to litedbmodel_runtime's op-agnostic Driver-backed executors (the exec SSoT); the wire
// classification is single-sourced in the runtime and bridged here by the wire_impls! macro (the
// orphan rule forbids the module-local wire trait impls living in the runtime crate).
use super::generated_txnestedcreate::*;
use litedbmodel_runtime::{Driver, SqlFailure, Value, Wire};
// The dialect is a CONNECTION property (`self.driver.dialect()`), not baked here — the generated
// SQL is dialect-neutral in its placeholders (`?`); the runtime renumbers `?`→`$N` per connection.

litedbmodel_runtime::wire_impls!();

/// Map a runtime SQL failure to the module-local BehaviorError (byte-equal codes: the bc runner
/// re-wraps a node failure as OP_FAILED regardless, so only the message/detail cross this seam).
fn cvt(e: SqlFailure) -> BehaviorError { BehaviorError::new(e.kind, e.message) }

struct TxRt<'a, 'b, 'c> { ctx: &'a litedbmodel_runtime::ExecutionContext<'b, 'c> }
impl<'a, 'b, 'c> HandlerNRTxNestedCreate for TxRt<'a, 'b, 'c> {
    type Wire = Wire;
    fn node_tx_body_0(&self, ports: &PortsNRTxNestedCreateTxBody0, _bound: Option<String>) -> Result<Wire, BehaviorError> {
        litedbmodel_runtime::exec(self.ctx, &ports.f_sql, &[litedbmodel_runtime::wp(&ports.f_p0), litedbmodel_runtime::wp(&ports.f_p1)], litedbmodel_runtime::ExecMode::RowSingle).map_err(cvt)
    }
    fn node_tx_body_1(&self, ports: &PortsNRTxNestedCreateTxBody1, _bound: Option<String>) -> Result<Wire, BehaviorError> {
        litedbmodel_runtime::exec(self.ctx, &ports.f_sql, &[litedbmodel_runtime::wp(&ports.f_p0), litedbmodel_runtime::wp(&ports.f_p1)], litedbmodel_runtime::ExecMode::RowSingle).map_err(cvt)
    }
}

/// The litedbmodel-consumer entry: run the RETURNING-chained transaction (BEGIN…COMMIT / ROLLBACK
/// via the runtime tx envelope; every statement runs on the ONE pinned tx-scoped ctx). Returns
/// `true` when the chain committed, `false` on rollback.
pub fn run(driver: &dyn Driver, in_: InNRTxNestedCreate) -> Result<bool, BehaviorError> {
    litedbmodel_runtime::run_transaction(driver, |ctx| run_native_raw_struct_TxNestedCreate(&TxRt { ctx }, in_)).map_err(cvt)
}

/// The OPTIONS-aware / ROUTED tx entry (#135): open the tx from a ConnSource (single driver, or the
/// WRITER pool of a named connection) and apply the TransactionOptions (isolation prelude,
/// rollback_only). Drives the SAME per-execution-ownership tx seam. Returns `true` iff it committed.
pub fn run_on(src: litedbmodel_runtime::ConnSource, connection: Option<&str>, dialect: litedbmodel_runtime::TxDialect, options: &litedbmodel_runtime::TransactionOptions, in_: InNRTxNestedCreate) -> Result<bool, BehaviorError> {
    litedbmodel_runtime::run_transaction_on(src, connection, dialect, options, |ctx| run_native_raw_struct_TxNestedCreate(&TxRt { ctx }, in_)).map_err(cvt)
}
