#![allow(dead_code, unused_imports, non_snake_case, clippy::all)]
// GENERATED by litedbmodel codegen — the RUST COMPANION for `generated_updatemany` (epic #123/#124).
// bc emits the runtime-free native module (ports + de-box runner + wire traits); litedbmodel emits
// THIS companion — the boundary-injected node_* handlers + wire adapter (bc C4). Every node_*
// delegates to litedbmodel_runtime's op-agnostic Driver-backed executors (the exec SSoT); the wire
// classification is single-sourced in the runtime and bridged here by the wire_impls! macro (the
// orphan rule forbids the module-local wire trait impls living in the runtime crate).
use super::generated_updatemany::*;
use litedbmodel_runtime::{Driver, SqlFailure, Value, Wire};
// The dialect is a CONNECTION property (`self.driver.dialect()`), not baked here — the generated
// SQL is dialect-neutral in its placeholders (`?`); the runtime renumbers `?`→`$N` per connection.

litedbmodel_runtime::wire_impls!();

/// Map a runtime SQL failure to the module-local BehaviorError (byte-equal codes: the bc runner
/// re-wraps a node failure as OP_FAILED regardless, so only the message/detail cross this seam).
fn cvt(e: SqlFailure) -> BehaviorError { BehaviorError::new(e.kind, e.message) }

pub struct Rt<'a> { driver: &'a dyn Driver }
impl<'a> HandlerNRUpdateMany for Rt<'a> {
    type Wire = Wire;
    fn node_n0(&self, ports: &PortsNRUpdateManyN0, _bound: Option<String>) -> Result<Wire, BehaviorError> {
        let cells: Vec<Vec<Value>> = vec![ports.f_v0.iter().map(|v| litedbmodel_runtime::wp(v)).collect::<Vec<Value>>(), ports.f_v1.iter().map(|v| litedbmodel_runtime::wp(v)).collect::<Vec<Value>>()];
        let params = litedbmodel_runtime::build_batch_params(&["id", "name"], &cells, litedbmodel_runtime::ArrayParamShape::SingleJson, ports.f_sql.matches('?').count());
        litedbmodel_runtime::exec(&litedbmodel_runtime::for_driver(self.driver), &ports.f_sql, &params, litedbmodel_runtime::ExecMode::Rows).map_err(cvt)
    }
}

/// The litedbmodel-consumer entry: build the runtime-backed handler for `UpdateMany`. The consumer
/// calls `run_native_raw_struct_UpdateMany(&handler(driver), in_)` — supplying NO node_* itself.
pub fn handler(driver: &dyn Driver) -> Rt<'_> { Rt { driver } }
