#![allow(dead_code, unused_imports, non_snake_case)]
// GENERATED by behavior-contracts (bc#90, rust-typed-native — the RUNTIME-FREE read de-box; STRUCT-ONLY,
// FULLY-NATIVE). A covered read is a strictly-sequential typed componentRef chain (point reads +
// relationKind:single children), emitted ONLY as a STRUCT-returning runner GENERIC over a per-component
// CONCRETE handler trait (HandlerNR<comp>): native ports struct IN (direct construction — every port is a
// CONCRETE Rust value: String / bool / Vec<&str> projection / i64 limit — NO boxed Value, NO by-name
// accessor); the handler takes a typed produced-aware 'bound' Option and returns the node's CONCRETE row
// struct (typed fields = the projected outType), and the runner reads row.<field> DIRECTLY into the node's
// outType struct. The covered plane carries NO bc-runtime reference at all — failures use the LOCAL
// BehaviorError (same codes, byte-equal to run_behavior). INLINE sequential (no plan driver) so a relation
// child reads the parent's REAL struct result via direct field access and the child-present decision is
// made from the real parent value — relationSingle / connection converge with run_behavior (fixes
// #323/#74). The exposed API is run_native_raw_struct_<comp>(handlers, in_) over the CONCRETE InNR_<comp>
// input struct + the CONCRETE HandlerNR<comp> trait (the consumer builds/implements both, keeping the
// model native). This module is FULLY NATIVE: a naive grep for boxing primitives OR for the bc-runtime
// crate finds nothing, by design (bc#90 / runtime-free).
use std::cell::RefCell;

// Local concrete failure type (runtime-free) — a covered runner returns Result<T, BehaviorError> over
// THIS local type instead of a bc-runtime failure, so the fully-covered module imports ZERO bc runtime.
// BehaviorError — the LOCAL concrete failure type for the covered read plane (runtime-free): a
// covered runner returns `Result<T, BehaviorError>` over THIS local type instead of a bc-runtime
// failure, so the fully-covered module imports ZERO bc runtime. Codes match run_behavior verbatim
// (byte-equal). The observe companion (test glue, a super:: submodule) bridges this local error to the
// bc-runtime BehaviorError at the observe boundary — the covered module itself stays runtime-free.
#[derive(Debug, Clone)]
pub struct BehaviorError {
    pub code: String,
    pub message: String,
}

impl BehaviorError {
    pub fn new(code: impl Into<String>, message: impl Into<String>) -> Self {
        BehaviorError { code: code.into(), message: message.into() }
    }
    /// The stable failure code (byte-equal to run_behavior) WITHOUT a bc-runtime type.
    pub fn code(&self) -> &str {
        &self.code
    }
}

impl std::fmt::Display for BehaviorError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}: {}", self.code, self.message)
    }
}
impl std::error::Error for BehaviorError {}

#[derive(Clone, Default)]
#[allow(dead_code)]
pub struct T0 {
    pub id: i64, // "id"
    pub title: String, // "title"
    pub author_id: i64, // "author_id"
}

#[derive(Clone, Default)]
#[allow(dead_code)]
pub struct T1 {
    pub id: i64, // "id"
    pub name: String, // "name"
}

#[derive(Clone, Default)]
#[allow(dead_code)]
pub struct T2 {
    pub authors: Vec<Vec<T1>>, // "authors"
    pub posts: Vec<T0>, // "posts"
}

#[allow(dead_code)]
fn unknown_component(component: &str) -> BehaviorError {
    BehaviorError::new("UNKNOWN_COMPONENT", format!("component '{component}' has no handler (fail-closed)"))
}

// Native ports structs (one per componentRef node; typed per the static port type — CONCRETE).
// PortsNRPostsWithAuthorN0 — CONCRETE native ports for node 'n0' (Select). Typed fields per the
// static port type; constructed directly (no Vec, no heap key strings, no per-port Value boxing). The
// handler reads the typed fields directly off this concrete struct — no by-name accessor.
#[derive(Clone)]
pub struct PortsNRPostsWithAuthorN0 {
    pub f_sql: String, // "sql"
    pub f_p0: i64, // "p0"
}

// PortsNRPostsWithAuthorN1 — CONCRETE native ports for node 'n1' (Select). Typed fields per the
// static port type; constructed directly (no Vec, no heap key strings, no per-port Value boxing). The
// handler reads the typed fields directly off this concrete struct — no by-name accessor.
#[derive(Clone)]
pub struct PortsNRPostsWithAuthorN1 {
    pub f_sql: String, // "sql"
    pub f_p0: i64, // "p0"
}

// PortsNRPostsWithAuthorN1Batch — CONCRETE batched ports for map 'n1': the Vec of per-element CONCRETE ports structs
// (a Vec<PortsNRPostsWithAuthorN1>, NOT a generic key-value container). The consumer's batched handler reads the typed
// element ports off the concrete struct directly.
#[derive(Clone)]
pub struct PortsNRPostsWithAuthorN1Batch {
    pub items: Vec<PortsNRPostsWithAuthorN1>,
}

// CONCRETE per-node row structs (typed fields = the node's outType; + error signal).
// RawRowNRPostsWithAuthorN0 — CONCRETE handler-result row (typed fields = the node's outType; + error signal).
#[derive(Default)]
pub struct RawRowNRPostsWithAuthorN0 {
    pub is_error: bool,
    pub err: String,
    pub val: Vec<T0>,
}

// RawElemNRPostsWithAuthorN1 — CONCRETE handler-result row (typed fields = the node's outType; + error signal).
#[derive(Default)]
pub struct RawElemNRPostsWithAuthorN1 {
    pub is_error: bool,
    pub err: String,
    pub val: Vec<T1>,
}

// RawRowNRPostsWithAuthorN1 — the BATCH row for map 'n1': the aligned per-element rows.
#[derive(Default)]
pub struct RawRowNRPostsWithAuthorN1 {
    pub is_error: bool,
    pub err: String,
    pub rows: Vec<RawElemNRPostsWithAuthorN1>,
}

// CONCRETE per-component input structs (fields = inputPorts).
// InNRPostsWithAuthor — the CONCRETE input for 'PostsWithAuthor' (fields = inputPorts; typed, consumer-built —
// NO generic Value slice, NO per-field boxing crosses the covered read boundary).
#[derive(Default)]
pub struct InNRPostsWithAuthor {
    pub author_id: i64, // "author_id"
}

// CONCRETE per-component handler traits (one node_* method per node — native ports IN, row OUT).
// HandlerNRPostsWithAuthor — the CONCRETE per-component handler seam: one typed method
// per covered node (native ports struct IN, concrete row struct OUT). No generic boxed-ports
// / boxed-value / dynamic accessor crosses the covered boundary — the consumer implements each
// node_* with a decode of its own wire payload into the concrete row (see INTEGRATION.md §6).
pub trait HandlerNRPostsWithAuthor {
    fn node_n0(&self, ports: &PortsNRPostsWithAuthorN0, bound: Option<String>) -> Option<RawRowNRPostsWithAuthorN0>;
    fn node_n1(&self, ports: &PortsNRPostsWithAuthorN1, bound: Option<String>) -> Option<RawElemNRPostsWithAuthorN1>;
}

// Combined read runners (STRUCT-returning — the fully de-plumbed CONCRETE path).
// run_native_raw_struct_PostsWithAuthor — the STRUCT-RETURNING combined read (bc#77/#87/#94): the fully
// de-plumbed CONCRETE path. Generic over the per-component CONCRETE HandlerNRPostsWithAuthor trait,
// whose node_* methods take the node's native ports struct and return the concrete per-node row
// struct (typed fields = the outType). The runner builds each ports struct by direct native
// construction (a simple string port lowers to a native Rust expr), dispatches the concrete
// node_* method, and reads row.<field> DIRECTLY into the node's outType struct cell — no boxed
// handler result, no generic enum crossing, no dispatch on a dynamic value on the covered plane. Node
// results are typed struct cells; a relation child reads the parent's REAL struct result via
// direct field access (child-present decision from the real parent value — relationSingle /
// connection converge). A real-concurrency stage (bc#87) is static parallel orchestration —
// scoped worker threads (bounded by the static plan.concurrency) call the concrete node_*
// method; preflight + interpret are committed in ascending index order so the value / op
// multiset / failure precedence byte-match run_behavior. The output is a typed struct/value
// assembled by struct literal + field access — the consumer keeps it native.
pub fn run_native_raw_struct_PostsWithAuthor<H: HandlerNRPostsWithAuthor>(
    handlers: &H,
    in_: InNRPostsWithAuthor,
) -> Result<T2, BehaviorError> {
    let cell_n0: RefCell<Vec<T0>> = RefCell::new(Default::default());
    let produced_n0 = std::cell::Cell::new(false);
    let _ = &produced_n0;
    let cell_n1: RefCell<Vec<Vec<T1>>> = RefCell::new(Default::default());
    let produced_n1 = std::cell::Cell::new(false);
    let _ = &produced_n1;
    // ── op 'n0' (Select) ──
    let ports_n0 = PortsNRPostsWithAuthorN0 { f_sql: "SELECT id, title, author_id FROM benchmark_posts WHERE author_id = ? ORDER BY id ASC".to_string(), f_p0: in_.author_id };
    let row_n0 = match handlers.node_n0(&ports_n0, None) {
        Some(r) => r,
        None => return Err(unknown_component("Select")),
    };
    if row_n0.is_error {
        return Err(BehaviorError::new("OP_FAILED", format!("operation '{}' failed under 'fail' policy: {}", "n0", row_n0.err)));
    }
    *cell_n0.borrow_mut() = row_n0.val;
    produced_n0.set(true);
    // ── map 'n1' (Select, per-element, into:null, parent:n0) ──
    if produced_n0.get() {
        let over_n1 = cell_n0.borrow().clone();
        let mut built_n1: Vec<Vec<T1>> = Vec::with_capacity(over_n1.len());
        for oel_n1 in over_n1.iter() {
            let ep_n1 = PortsNRPostsWithAuthorN1 { f_sql: "SELECT id, name FROM benchmark_users WHERE id = ?".to_string(), f_p0: oel_n1.author_id };
            let er_n1 = match handlers.node_n1(&ep_n1, None) {
                Some(r) => r,
                None => return Err(unknown_component("Select")),
            };
            if er_n1.is_error {
                return Err(BehaviorError::new("OP_FAILED", format!("operation '{}' failed under 'fail' policy: {}", "n1", er_n1.err)));
            }
            let _ = &oel_n1;
            let el_n1 = er_n1.val;
            built_n1.push(el_n1);
        }
        *cell_n1.borrow_mut() = built_n1;
        produced_n1.set(true);
    }
    let __out = T2 { authors: cell_n1.borrow().clone(), posts: cell_n0.borrow().clone() };
    Ok(__out)
}

// COMPONENT_NAMES_NATIVE_RAW — covered reads exposed on the combined struct-native path. Each is
// driven via run_native_raw_struct_<comp>(handlers, in_) -> Result<T, BehaviorError>: a STRUCT return
// (the consumer builds the CONCRETE InNR_<comp> input + implements the CONCRETE HandlerNR<comp> trait).
// See INTEGRATION.md §6.
pub const COMPONENT_NAMES_NATIVE_RAW: [&str; 1] = ["PostsWithAuthor"];
