#![allow(dead_code, unused_imports, non_snake_case)]
// GENERATED by behavior-contracts (bc#90, rust-typed-native — the RUNTIME-FREE read de-box; STRUCT-ONLY,
// FULLY-NATIVE). A covered read is a strictly-sequential typed componentRef chain (point reads +
// relationKind:single children), emitted ONLY as a STRUCT-returning runner GENERIC over a per-component
// CONCRETE handler trait (HandlerNR<comp>): native ports struct IN (direct construction — every port is a
// CONCRETE Rust value: String / bool / Vec<&str> projection / i64 limit — NO boxed Value, NO by-name
// accessor); the handler takes a typed produced-aware 'bound' Option and returns the node's CONCRETE row
// struct (typed fields = the projected outType), and the runner reads row.<field> DIRECTLY into the node's
// outType struct. The covered plane carries NO bc-runtime reference at all — failures use the LOCAL
// BehaviorError (same codes, byte-equal to run_behavior). INLINE sequential (no plan driver) so a relation
// child reads the parent's REAL struct result via direct field access and the child-present decision is
// made from the real parent value — relationSingle / connection converge with run_behavior (fixes
// #323/#74). The exposed API is run_native_raw_struct_<comp>(handlers, in_) over the CONCRETE InNR_<comp>
// input struct + the CONCRETE HandlerNR<comp> trait (the consumer builds/implements both, keeping the
// model native). This module is FULLY NATIVE: a naive grep for boxing primitives OR for the bc-runtime
// crate finds nothing, by design (bc#90 / runtime-free).
use std::cell::RefCell;

// Local concrete failure type (runtime-free) — a covered runner returns Result<T, BehaviorError> over
// THIS local type instead of a bc-runtime failure, so the fully-covered module imports ZERO bc runtime.
// BehaviorError — the LOCAL concrete failure type for the covered read plane (runtime-free): a
// covered runner returns `Result<T, BehaviorError>` over THIS local type instead of a bc-runtime
// failure, so the fully-covered module imports ZERO bc runtime. Codes match run_behavior verbatim
// (byte-equal). The observe companion (test glue, a super:: submodule) bridges this local error to the
// bc-runtime BehaviorError at the observe boundary — the covered module itself stays runtime-free.
#[derive(Debug, Clone)]
pub struct BehaviorError {
    pub code: String,
    pub message: String,
}

impl BehaviorError {
    pub fn new(code: impl Into<String>, message: impl Into<String>) -> Self {
        BehaviorError { code: code.into(), message: message.into() }
    }
    /// The stable failure code (byte-equal to run_behavior) WITHOUT a bc-runtime type.
    pub fn code(&self) -> &str {
        &self.code
    }
}

impl std::fmt::Display for BehaviorError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}: {}", self.code, self.message)
    }
}
impl std::error::Error for BehaviorError {}

#[derive(Clone, Default)]
#[allow(dead_code)]
pub struct T0 {
    pub id: i64, // "id"
    pub title: String, // "title"
    pub author_id: i64, // "author_id"
    pub published: i64, // "published"
}

#[allow(dead_code)]
fn unknown_component(component: &str) -> BehaviorError {
    BehaviorError::new("UNKNOWN_COMPONENT", format!("component '{component}' has no handler (fail-closed)"))
}

// Native ports structs (one per componentRef node; typed per the static port type — CONCRETE).
// PortsNRByAuthorMaybePublishedN0 — CONCRETE native ports for node 'n0' (Select). Typed fields per the
// static port type; constructed directly (no Vec, no heap key strings, no per-port Value boxing). The
// handler reads the typed fields directly off this concrete struct — no by-name accessor.
#[derive(Clone)]
pub struct PortsNRByAuthorMaybePublishedN0 {
    pub f_sql_head: String, // "sql_head"
    pub f_sql_tail: String, // "sql_tail"
    pub f_w0: String, // "w0"
    pub f_w0p0: i64, // "w0p0"
    pub f_w1: String, // "w1"
    pub f_w1p0: Option<i64>, // "w1p0"
}

// CONCRETE per-node row structs (typed fields = the node's outType; + error signal).
// RawRowNRByAuthorMaybePublishedN0 — CONCRETE handler-result row (typed fields = the node's outType; + error signal).
#[derive(Default)]
pub struct RawRowNRByAuthorMaybePublishedN0 {
    pub is_error: bool,
    pub err: String,
    pub val: Vec<T0>,
}

// CONCRETE per-component input structs (fields = inputPorts).
// InNRByAuthorMaybePublished — the CONCRETE input for 'ByAuthorMaybePublished' (fields = inputPorts; typed, consumer-built —
// NO generic Value slice, NO per-field boxing crosses the covered read boundary).
#[derive(Default)]
pub struct InNRByAuthorMaybePublished {
    pub author_id: i64, // "author_id"
    pub published: Option<i64>, // "published"
}

// CONCRETE per-component handler traits (one node_* method per node — native ports IN, row OUT).
// HandlerNRByAuthorMaybePublished — the CONCRETE per-component handler seam: one typed method
// per covered node (native ports struct IN, concrete row struct OUT). No generic boxed-ports
// / boxed-value / dynamic accessor crosses the covered boundary — the consumer implements each
// node_* with a decode of its own wire payload into the concrete row (see INTEGRATION.md §6).
pub trait HandlerNRByAuthorMaybePublished {
    fn node_n0(&self, ports: &PortsNRByAuthorMaybePublishedN0, bound: Option<String>) -> Option<RawRowNRByAuthorMaybePublishedN0>;
}

// Combined read runners (STRUCT-returning — the fully de-plumbed CONCRETE path).
// run_native_raw_struct_ByAuthorMaybePublished — the STRUCT-RETURNING combined read (bc#77/#87/#94): the fully
// de-plumbed CONCRETE path. Generic over the per-component CONCRETE HandlerNRByAuthorMaybePublished trait,
// whose node_* methods take the node's native ports struct and return the concrete per-node row
// struct (typed fields = the outType). The runner builds each ports struct by direct native
// construction (a simple string port lowers to a native Rust expr), dispatches the concrete
// node_* method, and reads row.<field> DIRECTLY into the node's outType struct cell — no boxed
// handler result, no generic enum crossing, no dispatch on a dynamic value on the covered plane. Node
// results are typed struct cells; a relation child reads the parent's REAL struct result via
// direct field access (child-present decision from the real parent value — relationSingle /
// connection converge). A real-concurrency stage (bc#87) is static parallel orchestration —
// scoped worker threads (bounded by the static plan.concurrency) call the concrete node_*
// method; preflight + interpret are committed in ascending index order so the value / op
// multiset / failure precedence byte-match run_behavior. The output is a typed struct/value
// assembled by struct literal + field access — the consumer keeps it native.
pub fn run_native_raw_struct_ByAuthorMaybePublished<H: HandlerNRByAuthorMaybePublished>(
    handlers: &H,
    in_: InNRByAuthorMaybePublished,
) -> Result<Vec<T0>, BehaviorError> {
    let cell_n0: RefCell<Vec<T0>> = RefCell::new(Default::default());
    let produced_n0 = std::cell::Cell::new(false);
    let _ = &produced_n0;
    // ── op 'n0' (Select) ──
    let ports_n0 = PortsNRByAuthorMaybePublishedN0 { f_sql_head: "SELECT id, title, author_id, published FROM benchmark_posts".to_string(), f_sql_tail: " ORDER BY id ASC".to_string(), f_w0: "author_id = ?".to_string(), f_w0p0: in_.author_id, f_w1: "published = ?".to_string(), f_w1p0: in_.published };
    let row_n0 = match handlers.node_n0(&ports_n0, None) {
        Some(r) => r,
        None => return Err(unknown_component("Select")),
    };
    if row_n0.is_error {
        return Err(BehaviorError::new("OP_FAILED", format!("operation '{}' failed under 'fail' policy: {}", "n0", row_n0.err)));
    }
    *cell_n0.borrow_mut() = row_n0.val;
    produced_n0.set(true);
    let __out = cell_n0.borrow().clone();
    Ok(__out)
}

// COMPONENT_NAMES_NATIVE_RAW — covered reads exposed on the combined struct-native path. Each is
// driven via run_native_raw_struct_<comp>(handlers, in_) -> Result<T, BehaviorError>: a STRUCT return
// (the consumer builds the CONCRETE InNR_<comp> input + implements the CONCRETE HandlerNR<comp> trait).
// See INTEGRATION.md §6.
pub const COMPONENT_NAMES_NATIVE_RAW: [&str; 1] = ["ByAuthorMaybePublished"];
