#![allow(dead_code, unused_imports, non_snake_case)]
// GENERATED by behavior-contracts (bc#90, rust-typed-native — the RUNTIME-FREE read de-box; STRUCT-ONLY,
// FULLY-NATIVE). A covered read is a strictly-sequential typed componentRef chain (point reads +
// relationKind:single children), emitted ONLY as a STRUCT-returning runner GENERIC over a per-component
// CONCRETE handler trait (HandlerNR<comp>): native ports struct IN (direct construction — every port is a
// CONCRETE Rust value: String / bool / Vec<&str> projection / i64 limit — NO boxed Value, NO by-name
// accessor); the handler takes a typed produced-aware 'bound' Option and returns the node's CONCRETE row
// struct (typed fields = the projected outType), and the runner reads row.<field> DIRECTLY into the node's
// outType struct. The covered plane carries NO bc-runtime reference at all — failures use the LOCAL
// BehaviorError (same codes, byte-equal to run_behavior). INLINE sequential (no plan driver) so a relation
// child reads the parent's REAL struct result via direct field access and the child-present decision is
// made from the real parent value — relationSingle / connection converge with run_behavior (fixes
// #323/#74). The exposed API is run_native_raw_struct_<comp>(handlers, in_) over the CONCRETE InNR_<comp>
// input struct + the CONCRETE HandlerNR<comp> trait (the consumer builds/implements both, keeping the
// model native). This module is FULLY NATIVE: a naive grep for boxing primitives OR for the bc-runtime
// crate finds nothing, by design (bc#90 / runtime-free).
use std::cell::RefCell;

// Local concrete failure type (runtime-free) — a covered runner returns Result<T, BehaviorError> over
// THIS local type instead of a bc-runtime failure, so the fully-covered module imports ZERO bc runtime.
// BehaviorError — the LOCAL concrete failure type for the covered read plane (runtime-free): a
// covered runner returns `Result<T, BehaviorError>` over THIS local type instead of a bc-runtime
// failure, so the fully-covered module imports ZERO bc runtime. Codes match run_behavior verbatim
// (byte-equal). The observe companion (test glue, a super:: submodule) bridges this local error to the
// bc-runtime BehaviorError at the observe boundary — the covered module itself stays runtime-free.
#[derive(Debug, Clone)]
pub struct BehaviorError {
    pub code: String,
    pub message: String,
}

impl BehaviorError {
    pub fn new(code: impl Into<String>, message: impl Into<String>) -> Self {
        BehaviorError { code: code.into(), message: message.into() }
    }
    /// The stable failure code (byte-equal to run_behavior) WITHOUT a bc-runtime type.
    pub fn code(&self) -> &str {
        &self.code
    }
}

impl std::fmt::Display for BehaviorError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}: {}", self.code, self.message)
    }
}
impl std::error::Error for BehaviorError {}

#[derive(Clone, Default)]
#[allow(dead_code)]
pub struct T0 {
    pub id: i64, // "id"
    pub name: String, // "name"
}

#[derive(Clone, Default)]
#[allow(dead_code)]
pub struct T1 {
    pub id: i64, // "id"
    pub title: String, // "title"
}

#[derive(Clone, Default)]
#[allow(dead_code)]
pub struct T2 {
    pub user: T0, // "user"
    pub post: T1, // "post"
}

#[allow(dead_code)]
fn unknown_component(component: &str) -> BehaviorError {
    BehaviorError::new("UNKNOWN_COMPONENT", format!("component '{component}' has no handler (fail-closed)"))
}

// Native ports structs (one per componentRef node; typed per the static port type — CONCRETE).
// PortsNRTxNestedUpdateTxBody0 — CONCRETE native ports for node 'tx_body_0' (Update). Typed fields per the
// static port type; constructed directly (no Vec, no heap key strings, no per-port Value boxing). The
// handler reads the typed fields directly off this concrete struct — no by-name accessor.
#[derive(Clone)]
pub struct PortsNRTxNestedUpdateTxBody0 {
    pub f_sql: String, // "sql"
    pub f_p0: String, // "p0"
    pub f_p1: i64, // "p1"
}

// PortsNRTxNestedUpdateTxBody1 — CONCRETE native ports for node 'tx_body_1' (Update). Typed fields per the
// static port type; constructed directly (no Vec, no heap key strings, no per-port Value boxing). The
// handler reads the typed fields directly off this concrete struct — no by-name accessor.
#[derive(Clone)]
pub struct PortsNRTxNestedUpdateTxBody1 {
    pub f_sql: String, // "sql"
    pub f_p0: String, // "p0"
    pub f_p1: i64, // "p1"
}

// CONCRETE per-node row structs (typed fields = the node's outType; + error signal).
// RawRowNRTxNestedUpdateTxBody0 — CONCRETE handler-result row (typed fields = the node's outType; + error signal).
#[derive(Default)]
pub struct RawRowNRTxNestedUpdateTxBody0 {
    pub is_error: bool,
    pub err: String,
    pub id: i64, // "id"
    pub name: String, // "name"
}

// RawRowNRTxNestedUpdateTxBody1 — CONCRETE handler-result row (typed fields = the node's outType; + error signal).
#[derive(Default)]
pub struct RawRowNRTxNestedUpdateTxBody1 {
    pub is_error: bool,
    pub err: String,
    pub id: i64, // "id"
    pub title: String, // "title"
}

// CONCRETE per-component input structs (fields = inputPorts).
// InNRTxNestedUpdate — the CONCRETE input for 'TxNestedUpdate' (fields = inputPorts; typed, consumer-built —
// NO generic Value slice, NO per-field boxing crosses the covered read boundary).
#[derive(Default)]
pub struct InNRTxNestedUpdate {
    pub name: String, // "name"
    pub user_id: i64, // "user_id"
    pub title: String, // "title"
}

// CONCRETE per-component handler traits (one node_* method per node — native ports IN, row OUT).
// HandlerNRTxNestedUpdate — the CONCRETE per-component handler seam: one typed method
// per covered node (native ports struct IN, concrete row struct OUT). No generic boxed-ports
// / boxed-value / dynamic accessor crosses the covered boundary — the consumer implements each
// node_* with a decode of its own wire payload into the concrete row (see INTEGRATION.md §6).
pub trait HandlerNRTxNestedUpdate {
    fn node_tx_body_0(&self, ports: &PortsNRTxNestedUpdateTxBody0, bound: Option<String>) -> Option<RawRowNRTxNestedUpdateTxBody0>;
    fn node_tx_body_1(&self, ports: &PortsNRTxNestedUpdateTxBody1, bound: Option<String>) -> Option<RawRowNRTxNestedUpdateTxBody1>;
}

// Combined read runners (STRUCT-returning — the fully de-plumbed CONCRETE path).
// run_native_raw_struct_TxNestedUpdate — the STRUCT-RETURNING combined read (bc#77/#87/#94): the fully
// de-plumbed CONCRETE path. Generic over the per-component CONCRETE HandlerNRTxNestedUpdate trait,
// whose node_* methods take the node's native ports struct and return the concrete per-node row
// struct (typed fields = the outType). The runner builds each ports struct by direct native
// construction (a simple string port lowers to a native Rust expr), dispatches the concrete
// node_* method, and reads row.<field> DIRECTLY into the node's outType struct cell — no boxed
// handler result, no generic enum crossing, no dispatch on a dynamic value on the covered plane. Node
// results are typed struct cells; a relation child reads the parent's REAL struct result via
// direct field access (child-present decision from the real parent value — relationSingle /
// connection converge). A real-concurrency stage (bc#87) is static parallel orchestration —
// scoped worker threads (bounded by the static plan.concurrency) call the concrete node_*
// method; preflight + interpret are committed in ascending index order so the value / op
// multiset / failure precedence byte-match run_behavior. The output is a typed struct/value
// assembled by struct literal + field access — the consumer keeps it native.
pub fn run_native_raw_struct_TxNestedUpdate<H: HandlerNRTxNestedUpdate>(
    handlers: &H,
    in_: InNRTxNestedUpdate,
) -> Result<T2, BehaviorError> {
    let cell_tx_body_0: RefCell<T0> = RefCell::new(Default::default());
    let produced_tx_body_0 = std::cell::Cell::new(false);
    let _ = &produced_tx_body_0;
    let cell_tx_body_1: RefCell<T1> = RefCell::new(Default::default());
    let produced_tx_body_1 = std::cell::Cell::new(false);
    let _ = &produced_tx_body_1;
    // ── op 'tx_body_0' (Update) ──
    let ports_tx_body_0 = PortsNRTxNestedUpdateTxBody0 { f_sql: "UPDATE benchmark_users SET name = ? WHERE id = ? RETURNING id, name".to_string(), f_p0: in_.name.clone(), f_p1: in_.user_id };
    let row_tx_body_0 = match handlers.node_tx_body_0(&ports_tx_body_0, None) {
        Some(r) => r,
        None => return Err(unknown_component("Update")),
    };
    if row_tx_body_0.is_error {
        return Err(BehaviorError::new("OP_FAILED", format!("operation '{}' failed under 'fail' policy: {}", "tx_body_0", row_tx_body_0.err)));
    }
    *cell_tx_body_0.borrow_mut() = T0 { id: row_tx_body_0.id, name: row_tx_body_0.name };
    produced_tx_body_0.set(true);
    // ── op 'tx_body_1' (Update) ──
    let ports_tx_body_1 = PortsNRTxNestedUpdateTxBody1 { f_sql: "UPDATE benchmark_posts SET title = ? WHERE author_id = ? RETURNING id, title".to_string(), f_p0: in_.title.clone(), f_p1: in_.user_id };
    let row_tx_body_1 = match handlers.node_tx_body_1(&ports_tx_body_1, None) {
        Some(r) => r,
        None => return Err(unknown_component("Update")),
    };
    if row_tx_body_1.is_error {
        return Err(BehaviorError::new("OP_FAILED", format!("operation '{}' failed under 'fail' policy: {}", "tx_body_1", row_tx_body_1.err)));
    }
    *cell_tx_body_1.borrow_mut() = T1 { id: row_tx_body_1.id, title: row_tx_body_1.title };
    produced_tx_body_1.set(true);
    let __out = T2 { user: cell_tx_body_0.borrow().clone(), post: cell_tx_body_1.borrow().clone() };
    Ok(__out)
}

// COMPONENT_NAMES_NATIVE_RAW — covered reads exposed on the combined struct-native path. Each is
// driven via run_native_raw_struct_<comp>(handlers, in_) -> Result<T, BehaviorError>: a STRUCT return
// (the consumer builds the CONCRETE InNR_<comp> input + implements the CONCRETE HandlerNR<comp> trait).
// See INTEGRATION.md §6.
pub const COMPONENT_NAMES_NATIVE_RAW: [&str; 1] = ["TxNestedUpdate"];
