#!/usr/bin/env bash
# E1 (#116, epic #115) PROOF-OF-APPROACH — the out-of-process verification legs.
#
# Prerequisite: the TS leg has emitted the artifacts into /tmp/e1proof —
#   npx vitest run test/scp/e1-native-sql-port.test.ts
# which writes generated modules and the seeded proof databases. No serialized sidecars are emitted.
#
# Legs:
#   1. BC-CORE BOUNDARY — every embedded bc core compiles with std only and has zero runtime/DB refs;
#      only its co-located litedbmodel adapter may depend on litedbmodel_runtime.
#   2. PURITY — the comment-stripped module names no boxing/JSON-interpreter primitive.
#   3. EXECUTION BYTE-EQUALITY — run the module (through the exec seam) against the seeded DB and
#      execute native generated entry points against the seeded database.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROOF_DIR=/tmp/e1proof
MODULES=(generated_findunique generated_byids generated_recent generated_bymaybe generated_capped generated_feed generated_tenantfeed generated_relbatch generated_relsingle generated_createuser generated_renameuser generated_deleteuser generated_upsert generated_createmany generated_upsertmany generated_updatemany generated_txdelete generated_txnestedcreate generated_txnestedupdate generated_txnestedupsert generated_txrollback)
WRITE_OPS=(createuser renameuser deleteuser)
fail=0

for m in "${MODULES[@]}"; do
  if [[ ! -f "$PROOF_DIR/$m.rs" ]]; then
    echo "FATAL: $PROOF_DIR/$m.rs missing — run: npx vitest run test/scp/e1-native-sql-port.test.ts" >&2
    exit 2
  fi
  # Keep the crate's sole generated module in lockstep (bc core + co-located static runtime adapter).
  cp "$PROOF_DIR/$m.rs" "$HERE/src/$m.rs"
done

work="$(mktemp -d)"

bc_core_is_pure() {
  local core="$1"
  ! grep -qE 'litedbmodel_runtime|serde_json|Node::parse|\.prepare\(|execute_relation_batch|build_relation_params' "$core"
}

echo "── leg 1: each in-file bc core is std-only; runtime dependency starts at the adapter boundary ──"
first_core=""
for m in "${MODULES[@]}"; do
  prefix="$work/$m.core"
  awk -v prefix="$prefix" '
    /^\/\/ GENERATED by behavior-contracts/ { n++; out=prefix "." n ".rs"; active=1 }
    /^\/\/ litedbmodel static runtime adapter/ { active=0 }
    active { print > out }
  ' "$PROOF_DIR/$m.rs"
  cores=("$prefix".*.rs)
  if [[ ! -e "${cores[0]}" ]]; then
    echo "  FAIL  $m: no bc core boundary marker"; fail=1; continue
  fi
  for core in "${cores[@]}"; do
    [[ -z "$first_core" ]] && first_core="$core"
    if ! bc_core_is_pure "$core"; then
      echo "  FAIL  $m: bc core crosses into litedbmodel runtime/DB execution"; fail=1
    elif rustc --edition 2021 --crate-name bc_core --crate-type lib -D dead-code --emit metadata -o "$core.rmeta" "$core" 2>"$work/err"; then
      echo "  PASS  $m/$(basename "$core"): std-only bc core, no private dead code"
    else
      echo "  FAIL  $m/$(basename "$core"): bc core did not compile std-only:"; sed 's/^/        /' "$work/err"; fail=1
    fi
  done
done

# Negative control: the same boundary checker must reject an injected runtime reference in a bc core.
negative="$work/negative-runtime-in-core.rs"
cp "$first_core" "$negative"
printf '\nfn injected_violation() { let _ = litedbmodel_runtime::ExecMode::Rows; }\n' >> "$negative"
if bc_core_is_pure "$negative"; then
  echo "  FAIL  negative control: runtime reference injected into bc core was accepted"; fail=1
else
  echo "  PASS  negative control: injected bc-core runtime reference was rejected"
fi

echo "── leg 2: purity — no boxing / JSON interpreter primitive in code (comments stripped) ──"
for m in "${MODULES[@]}"; do
  stripped="$work/$m.stripped.rs"
  perl -0777 -pe 's{("(?:[^"\\]|\\.)*")|//[^\n]*|/\*.*?\*/}{defined $1 ? $1 : ""}ges' "$PROOF_DIR/$m.rs" > "$stripped"
  bad=0
  for marker in 'serde_json' 'Box<dyn' 'dyn Any' 'run_behavior' 'behavior_contracts' 'RawValue' 'obj_native' 'run_plan'; do
    if grep -qF -- "$marker" "$stripped"; then echo "  FAIL  $m: found '$marker'"; bad=1; fail=1; fi
  done
  [[ $bad -eq 0 ]] && echo "  PASS  $m: no boxing/JSON interpreter primitive"
  # each module must carry its own SQL as a baked literal — either the single `f_sql` port, or the
  # fragmented skip shape's `f_sql_head` (head + baked WHERE fragments the seam assembles).
  if grep -qE 'f_sql(_head)?: "(SELECT|INSERT|UPDATE|DELETE)[^"]*"\.to_string\(\)' "$stripped"; then
    echo "  PASS  $m: the SQL is baked as a native literal IN the module"
  else
    echo "  FAIL  $m: the module does not carry its SQL"; fail=1
  fi
done

[[ $fail -eq 0 ]] || exit "$fail"

echo "── leg 3: direct native/interpreter result + DB-state oracle ──"
ROOT="$HERE/../.."
( cd "$ROOT" && node --import tsx benchmark/crosslang/oracle-fixture-build.ts )
cargo run --quiet --manifest-path "$ROOT/rust/Cargo.toml" -p litedbmodel_oracle -- sqlite /tmp/litedbmodel-oracle-e1.db
